-- VHDL Entity project1_lib.add_13.symbol
--
-- Created:
--          by - zmcgint2.ews (gelib-057-26.ews.illinois.edu)
--          at - 17:49:21 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY add_13 IS
   PORT( 
      input       : IN     std_logic_vector (7 DOWNTO 0);
      out_plus_13 : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END add_13 ;

--
-- VHDL Architecture project1_lib.add_13.struct
--
-- Created:
--          by - zmcgint2.ews (gelib-057-26.ews.illinois.edu)
--          at - 17:49:21 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF add_13 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL b   : std_logic;
   SIGNAL cin : std_logic;


   -- Component Declarations
   COMPONENT full_adder_8bit
   PORT (
      a    : IN     std_logic ;
      a1   : IN     std_logic ;
      a2   : IN     std_logic ;
      a3   : IN     std_logic ;
      a4   : IN     std_logic ;
      a5   : IN     std_logic ;
      a6   : IN     std_logic ;
      a7   : IN     std_logic ;
      b    : IN     std_logic ;
      b1   : IN     std_logic ;
      b2   : IN     std_logic ;
      b3   : IN     std_logic ;
      b4   : IN     std_logic ;
      b5   : IN     std_logic ;
      b6   : IN     std_logic ;
      b7   : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      s    : OUT    std_logic ;
      s1   : OUT    std_logic ;
      s2   : OUT    std_logic ;
      s3   : OUT    std_logic ;
      s4   : OUT    std_logic ;
      s5   : OUT    std_logic ;
      s6   : OUT    std_logic ;
      s7   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder_8bit USE ENTITY project1_lib.full_adder_8bit;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'gnd'
   cin <= '0';

   -- ModuleWare code(v1.9) for instance 'U_4' of 'vdd'
   b <= '1';

   -- Instance port mappings.
   U_2 : full_adder_8bit
      PORT MAP (
         a    => input(0),
         a1   => input(1),
         a2   => input(2),
         a3   => input(3),
         a4   => input(4),
         a5   => input(5),
         a6   => input(6),
         a7   => input(7),
         b    => cin,
         b1   => cin,
         b2   => b,
         b3   => b,
         b4   => cin,
         b5   => cin,
         b6   => cin,
         b7   => cin,
         cin  => cin,
         cout => OPEN,
         s    => out_plus_13(0),
         s1   => out_plus_13(1),
         s2   => out_plus_13(2),
         s3   => out_plus_13(3),
         s4   => out_plus_13(4),
         s5   => out_plus_13(5),
         s6   => out_plus_13(6),
         s7   => out_plus_13(7)
      );

END struct;
