-- VHDL Entity project1_lib.ascii_to_alphabet_bus.symbol
--
-- Created:
--          by - zmcgint2.ews (gelib-057-26.ews.illinois.edu)
--          at - 18:29:39 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ascii_to_alphabet_bus IS
   PORT( 
      ascii_in     : IN     std_logic_vector (7 DOWNTO 0);
      alphabet_out : OUT    std_logic_vector (7 DOWNTO 0);
      cout         : OUT    std_logic
   );

-- Declarations

END ascii_to_alphabet_bus ;

--
-- VHDL Architecture project1_lib.ascii_to_alphabet_bus.struct
--
-- Created:
--          by - zmcgint2.ews (gelib-057-26.ews.illinois.edu)
--          at - 18:29:39 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF ascii_to_alphabet_bus IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL b6   : std_logic;
   SIGNAL b7   : std_logic;
   SIGNAL dout : std_logic;


   -- Component Declarations
   COMPONENT full_adder_8bit
   PORT (
      a    : IN     std_logic ;
      a1   : IN     std_logic ;
      a2   : IN     std_logic ;
      a3   : IN     std_logic ;
      a4   : IN     std_logic ;
      a5   : IN     std_logic ;
      a6   : IN     std_logic ;
      a7   : IN     std_logic ;
      b    : IN     std_logic ;
      b1   : IN     std_logic ;
      b2   : IN     std_logic ;
      b3   : IN     std_logic ;
      b4   : IN     std_logic ;
      b5   : IN     std_logic ;
      b6   : IN     std_logic ;
      b7   : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      s    : OUT    std_logic ;
      s1   : OUT    std_logic ;
      s2   : OUT    std_logic ;
      s3   : OUT    std_logic ;
      s4   : OUT    std_logic ;
      s5   : OUT    std_logic ;
      s6   : OUT    std_logic ;
      s7   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder_8bit USE ENTITY project1_lib.full_adder_8bit;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'gnd'
   b6 <= '0';

   -- ModuleWare code(v1.9) for instance 'U_3' of 'gnd'
   dout <= '0';

   -- ModuleWare code(v1.9) for instance 'U_2' of 'vdd'
   b7 <= '1';

   -- Instance port mappings.
   U_0 : full_adder_8bit
      PORT MAP (
         a    => ascii_in(0),
         a1   => ascii_in(1),
         a2   => ascii_in(2),
         a3   => ascii_in(3),
         a4   => ascii_in(4),
         a5   => ascii_in(5),
         a6   => ascii_in(6),
         a7   => ascii_in(7),
         b    => b7,
         b1   => b7,
         b2   => b7,
         b3   => b7,
         b4   => b7,
         b5   => b6,
         b6   => b6,
         b7   => b7,
         cin  => dout,
         cout => cout,
         s    => alphabet_out(0),
         s1   => alphabet_out(1),
         s2   => alphabet_out(2),
         s3   => alphabet_out(3),
         s4   => alphabet_out(4),
         s5   => alphabet_out(5),
         s6   => alphabet_out(6),
         s7   => alphabet_out(7)
      );

END struct;
