-- VHDL Entity lab22_lib.full_adder.symbol
--
-- Created:
--          by - zmcgint2.ews (gelib-057-29.ews.illinois.edu)
--          at - 10:17:13 09/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY full_adder IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      cout : OUT    std_logic;
      s    : OUT    std_logic
   );

-- Declarations

END full_adder ;

--
-- VHDL Architecture lab22_lib.full_adder.struct
--
-- Created:
--          by - zmcgint2.ews (gelib-057-29.ews.illinois.edu)
--          at - 10:17:13 09/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lab22_lib;

ARCHITECTURE struct OF full_adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL f     : std_logic;


   -- Component Declarations
   COMPONENT myxor
   PORT (
      x : IN     std_logic ;
      y : IN     std_logic ;
      f : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : myxor USE ENTITY lab22_lib.myxor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout1 <= a AND b;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   dout <= f AND cin;

   -- Instance port mappings.
   U_0 : myxor
      PORT MAP (
         x => a,
         y => b,
         f => f
      );
   U_1 : myxor
      PORT MAP (
         x => dout,
         y => dout1,
         f => cout
      );
   U_2 : myxor
      PORT MAP (
         x => cin,
         y => f,
         f => s
      );

END struct;
