-- VHDL Entity project1_lib.inv_and_add1_bus.symbol
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 14:17:31 11/01/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY inv_and_add1_bus IS
   PORT( 
      pos_in  : IN     std_logic_vector (7 DOWNTO 0);
      neg_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END inv_and_add1_bus ;

--
-- VHDL Architecture project1_lib.inv_and_add1_bus.struct
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 14:17:32 11/01/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF inv_and_add1_bus IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL cout  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;
   SIGNAL dout8 : std_logic;
   SIGNAL dout9 : std_logic;


   -- Component Declarations
   COMPONENT full_adder_8bit
   PORT (
      a    : IN     std_logic ;
      a1   : IN     std_logic ;
      a2   : IN     std_logic ;
      a3   : IN     std_logic ;
      a4   : IN     std_logic ;
      a5   : IN     std_logic ;
      a6   : IN     std_logic ;
      a7   : IN     std_logic ;
      b    : IN     std_logic ;
      b1   : IN     std_logic ;
      b2   : IN     std_logic ;
      b3   : IN     std_logic ;
      b4   : IN     std_logic ;
      b5   : IN     std_logic ;
      b6   : IN     std_logic ;
      b7   : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      s    : OUT    std_logic ;
      s1   : OUT    std_logic ;
      s2   : OUT    std_logic ;
      s3   : OUT    std_logic ;
      s4   : OUT    std_logic ;
      s5   : OUT    std_logic ;
      s6   : OUT    std_logic ;
      s7   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder_8bit USE ENTITY project1_lib.full_adder_8bit;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_9' of 'gnd'
   dout <= '0';

   -- ModuleWare code(v1.9) for instance 'U_0' of 'inv'
   dout9 <= NOT(pos_in(7));

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout8 <= NOT(pos_in(6));

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout7 <= NOT(pos_in(5));

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout6 <= NOT(pos_in(4));

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout5 <= NOT(pos_in(3));

   -- ModuleWare code(v1.9) for instance 'U_5' of 'inv'
   dout4 <= NOT(pos_in(2));

   -- ModuleWare code(v1.9) for instance 'U_6' of 'inv'
   dout3 <= NOT(pos_in(1));

   -- ModuleWare code(v1.9) for instance 'U_7' of 'inv'
   dout2 <= NOT(pos_in(0));

   -- ModuleWare code(v1.9) for instance 'U_10' of 'vdd'
   dout1 <= '1';

   -- Instance port mappings.
   U_8 : full_adder_8bit
      PORT MAP (
         a    => dout2,
         a1   => dout3,
         a2   => dout4,
         a3   => dout5,
         a4   => dout6,
         a5   => dout7,
         a6   => dout8,
         a7   => dout9,
         b    => dout1,
         b1   => dout,
         b2   => dout,
         b3   => dout,
         b4   => dout,
         b5   => dout,
         b6   => dout,
         b7   => dout,
         cin  => dout,
         cout => cout,
         s    => neg_out(0),
         s1   => neg_out(1),
         s2   => neg_out(2),
         s3   => neg_out(3),
         s4   => neg_out(4),
         s5   => neg_out(5),
         s6   => neg_out(6),
         s7   => neg_out(7)
      );

END struct;
