-- VHDL Entity project1_lib.j7bitcomparator.symbol
--
-- Created:
--          by - jschen3.ews (gelib-057-16.ews.illinois.edu)
--          at - 18:30:16 10/15/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY j7bitcomparator IS
   PORT( 
      A0          : IN     std_logic;
      A1          : IN     std_logic;
      A2          : IN     std_logic;
      A3          : IN     std_logic;
      A4          : IN     std_logic;
      A5          : IN     std_logic;
      A6          : IN     std_logic;
      B0          : IN     std_logic;
      B1          : IN     std_logic;
      B2          : IN     std_logic;
      B3          : IN     std_logic;
      B4          : IN     std_logic;
      B5          : IN     std_logic;
      B6          : IN     std_logic;
      A7equalsB7  : OUT    std_logic;
      A7greaterB7 : OUT    std_logic;
      B7greaterA7 : OUT    std_logic
   );

-- Declarations

END j7bitcomparator ;

--
-- VHDL Architecture project1_lib.j7bitcomparator.struct
--
-- Created:
--          by - jschen3.ews (gelib-057-16.ews.illinois.edu)
--          at - 18:30:16 10/15/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF j7bitcomparator IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL AequalsB   : std_logic;
   SIGNAL AequalsB1  : std_logic;
   SIGNAL AequalsB2  : std_logic;
   SIGNAL AequalsB3  : std_logic;
   SIGNAL AequalsB4  : std_logic;
   SIGNAL AequalsB5  : std_logic;
   SIGNAL AequalsB6  : std_logic;
   SIGNAL BgreaterA  : std_logic;
   SIGNAL BgreaterA1 : std_logic;
   SIGNAL BgreaterA2 : std_logic;
   SIGNAL din0       : std_logic;
   SIGNAL din1       : std_logic;
   SIGNAL din10      : std_logic;
   SIGNAL din11      : std_logic;
   SIGNAL din12      : std_logic;
   SIGNAL din13      : std_logic;
   SIGNAL din2       : std_logic;
   SIGNAL din3       : std_logic;
   SIGNAL din4       : std_logic;
   SIGNAL din5       : std_logic;
   SIGNAL din6       : std_logic;
   SIGNAL din7       : std_logic;
   SIGNAL din8       : std_logic;
   SIGNAL din9       : std_logic;
   SIGNAL dout       : std_logic;
   SIGNAL dout1      : std_logic;
   SIGNAL dout2      : std_logic;
   SIGNAL dout3      : std_logic;
   SIGNAL dout4      : std_logic;
   SIGNAL dout5      : std_logic;
   SIGNAL dout6      : std_logic;
   SIGNAL dout7      : std_logic;
   SIGNAL dout8      : std_logic;


   -- Component Declarations
   COMPONENT j1bitcomparator
   PORT (
      A         : IN     std_logic ;
      B         : IN     std_logic ;
      AequalsB  : OUT    std_logic ;
      AgreaterB : OUT    std_logic ;
      BgreaterA : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : j1bitcomparator USE ENTITY project1_lib.j1bitcomparator;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_7' of 'and'
   A7equalsB7 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3
                 AND AequalsB4 AND AequalsB5 AND AequalsB6;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'and'
   din12 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3
            AND AequalsB4 AND AequalsB5 AND BgreaterA;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'and'
   dout7 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3
            AND AequalsB4 AND AequalsB5 AND din6;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'and'
   din11 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3
            AND AequalsB4 AND BgreaterA1;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'and'
   dout8 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3
            AND AequalsB4 AND din5;

   -- ModuleWare code(v1.9) for instance 'U_12' of 'and'
   din10 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3 AND din4;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'and'
   dout6 <= AequalsB AND AequalsB1 AND AequalsB2 AND AequalsB3 AND din7;

   -- ModuleWare code(v1.9) for instance 'U_14' of 'and'
   dout1 <= AequalsB AND AequalsB1 AND AequalsB2 AND din3;

   -- ModuleWare code(v1.9) for instance 'U_15' of 'and'
   dout5 <= AequalsB AND AequalsB1 AND AequalsB2 AND din8;

   -- ModuleWare code(v1.9) for instance 'U_16' of 'and'
   dout <= AequalsB AND AequalsB1 AND din2;

   -- ModuleWare code(v1.9) for instance 'U_17' of 'and'
   dout4 <= AequalsB AND AequalsB1 AND din9;

   -- ModuleWare code(v1.9) for instance 'U_18' of 'and'
   dout2 <= AequalsB AND din1;

   -- ModuleWare code(v1.9) for instance 'U_20' of 'and'
   dout3 <= AequalsB AND din13;

   -- ModuleWare code(v1.9) for instance 'U_19' of 'or'
   B7greaterA7 <= BgreaterA2 OR dout2 OR dout OR dout1 OR din10 OR din11
                  OR din12;

   -- ModuleWare code(v1.9) for instance 'U_21' of 'or'
   A7greaterB7 <= din0 OR dout3 OR dout4 OR dout5 OR dout6 OR dout8
                  OR dout7;

   -- Instance port mappings.
   U_0 : j1bitcomparator
      PORT MAP (
         A         => A6,
         B         => B6,
         AequalsB  => OPEN,
         AgreaterB => din0,
         BgreaterA => BgreaterA2
      );
   U_1 : j1bitcomparator
      PORT MAP (
         A         => A5,
         B         => B5,
         AequalsB  => OPEN,
         AgreaterB => din13,
         BgreaterA => din1
      );
   U_2 : j1bitcomparator
      PORT MAP (
         A         => A4,
         B         => B4,
         AequalsB  => OPEN,
         AgreaterB => din9,
         BgreaterA => din2
      );
   U_3 : j1bitcomparator
      PORT MAP (
         A         => A3,
         B         => B3,
         AequalsB  => OPEN,
         AgreaterB => din8,
         BgreaterA => din3
      );
   U_4 : j1bitcomparator
      PORT MAP (
         A         => A2,
         B         => B2,
         AequalsB  => OPEN,
         AgreaterB => din7,
         BgreaterA => din4
      );
   U_5 : j1bitcomparator
      PORT MAP (
         A         => A1,
         B         => B1,
         AequalsB  => OPEN,
         AgreaterB => din5,
         BgreaterA => BgreaterA1
      );
   U_6 : j1bitcomparator
      PORT MAP (
         A         => A0,
         B         => B0,
         AequalsB  => AequalsB6,
         AgreaterB => din6,
         BgreaterA => BgreaterA
      );

END struct;
