-- VHDL Entity project1_lib.railfenceencode.symbol
--
-- Created:
--          by - mhe5.ews (dcl-l520-36.ews.illinois.edu)
--          at - 21:15:00 10/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY railfenceencode IS
   PORT( 
      clk : IN     std_logic;
      d0  : IN     std_logic;
      d1  : IN     std_logic;
      d2  : IN     std_logic;
      d3  : IN     std_logic;
      d4  : IN     std_logic;
      d5  : IN     std_logic;
      d6  : IN     std_logic;
      d7  : IN     std_logic;
      g0  : OUT    std_logic;
      g1  : OUT    std_logic;
      g2  : OUT    std_logic;
      g4  : OUT    std_logic;
      g5  : OUT    std_logic;
      g6  : OUT    std_logic;
      q11 : OUT    std_logic;
      q15 : OUT    std_logic
   );

-- Declarations

END railfenceencode ;

--
-- VHDL Architecture project1_lib.railfenceencode.struct
--
-- Created:
--          by - mhe5.ews (dcl-l520-36.ews.illinois.edu)
--          at - 21:15:00 10/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY checkcode_lib;

ARCHITECTURE struct OF railfenceencode IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL q0  : std_logic;
   SIGNAL q1  : std_logic;
   SIGNAL q10 : std_logic;
   SIGNAL q12 : std_logic;
   SIGNAL q13 : std_logic;
   SIGNAL q14 : std_logic;
   SIGNAL q2  : std_logic;
   SIGNAL q3  : std_logic;
   SIGNAL q4  : std_logic;
   SIGNAL q5  : std_logic;
   SIGNAL q6  : std_logic;
   SIGNAL q7  : std_logic;
   SIGNAL q8  : std_logic;
   SIGNAL q9  : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL q11_internal : std_logic;
   SIGNAL q15_internal : std_logic;


   -- Component Declarations
   COMPONENT bintotwo
   PORT (
      b0 : IN     std_logic;
      b1 : IN     std_logic;
      b2 : IN     std_logic;
      b3 : IN     std_logic;
      g0 : OUT    std_logic;
      g1 : OUT    std_logic;
      g2 : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT fourbitreg
   PORT (
      clk : IN     std_logic;
      d0  : IN     std_logic;
      d1  : IN     std_logic;
      d2  : IN     std_logic;
      d3  : IN     std_logic;
      q0  : OUT    std_logic;
      q1  : OUT    std_logic;
      q2  : OUT    std_logic;
      q3  : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : bintotwo USE ENTITY checkcode_lib.bintotwo;
   FOR ALL : fourbitreg USE ENTITY checkcode_lib.fourbitreg;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : bintotwo
      PORT MAP (
         b0 => q8,
         b1 => q9,
         b2 => q10,
         b3 => q11_internal,
         g0 => g0,
         g1 => g1,
         g2 => g2
      );
   U_5 : bintotwo
      PORT MAP (
         b0 => q12,
         b1 => q13,
         b2 => q14,
         b3 => q15_internal,
         g0 => g4,
         g1 => g5,
         g2 => g6
      );
   U_0 : fourbitreg
      PORT MAP (
         clk => clk,
         d0  => d0,
         d1  => d1,
         d2  => d2,
         d3  => d3,
         q0  => q0,
         q1  => q1,
         q2  => q2,
         q3  => q3
      );
   U_1 : fourbitreg
      PORT MAP (
         clk => clk,
         d0  => d4,
         d1  => d5,
         d2  => d6,
         d3  => d7,
         q0  => q4,
         q1  => q5,
         q2  => q6,
         q3  => q7
      );
   U_2 : fourbitreg
      PORT MAP (
         clk => clk,
         d0  => q0,
         d1  => q2,
         d2  => q5,
         d3  => q7,
         q0  => q8,
         q1  => q9,
         q2  => q10,
         q3  => q11_internal
      );
   U_3 : fourbitreg
      PORT MAP (
         clk => clk,
         d0  => q1,
         d1  => q3,
         d2  => q4,
         d3  => q6,
         q0  => q12,
         q1  => q13,
         q2  => q14,
         q3  => q15_internal
      );

   -- Implicit buffered output assignments
   q11 <= q11_internal;
   q15 <= q15_internal;

END struct;
