-- VHDL Entity project1_lib.xor_encode.symbol
--
-- Created:
--          by - mhe5.ews (dcl-l520-36.ews.illinois.edu)
--          at - 21:59:48 10/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY xor_encode IS
   PORT( 
      c0    : IN     std_logic;
      c1    : IN     std_logic;
      c2    : IN     std_logic;
      c3    : IN     std_logic;
      c4    : IN     std_logic;
      c5    : IN     std_logic;
      c6    : IN     std_logic;
      c7    : IN     std_logic;
      d0    : IN     std_logic;
      d1    : IN     std_logic;
      d2    : IN     std_logic;
      d3    : IN     std_logic;
      d4    : IN     std_logic;
      d5    : IN     std_logic;
      d6    : IN     std_logic;
      d7    : IN     std_logic;
      dout  : OUT    std_logic;
      dout1 : OUT    std_logic;
      dout2 : OUT    std_logic;
      dout3 : OUT    std_logic;
      dout4 : OUT    std_logic;
      dout5 : OUT    std_logic;
      dout6 : OUT    std_logic;
      dout7 : OUT    std_logic
   );

-- Declarations

END xor_encode ;

--
-- VHDL Architecture project1_lib.xor_encode.struct
--
-- Created:
--          by - mhe5.ews (dcl-l520-36.ews.illinois.edu)
--          at - 21:59:48 10/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF xor_encode IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'sxor'
   dout <= d0 XOR c0;

   -- ModuleWare code(v1.9) for instance 'U_7' of 'sxor'
   dout1 <= d1 XOR c1;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'sxor'
   dout2 <= d2 XOR c2;

   -- ModuleWare code(v1.9) for instance 'U_9' of 'sxor'
   dout3 <= d3 XOR c3;

   -- ModuleWare code(v1.9) for instance 'U_10' of 'sxor'
   dout4 <= d4 XOR c4;

   -- ModuleWare code(v1.9) for instance 'U_11' of 'sxor'
   dout5 <= d5 XOR c5;

   -- ModuleWare code(v1.9) for instance 'U_12' of 'sxor'
   dout6 <= d6 XOR c6;

   -- ModuleWare code(v1.9) for instance 'U_13' of 'sxor'
   dout7 <= d7 XOR c7;

   -- Instance port mappings.

END struct;
