-- VHDL Entity Division_lib.SubstractorOneBit.symbol
--
-- Created:
--          by - jschen3.ews (evrt-252-06.ews.illinois.edu)
--          at - 19:23:23 11/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY SubstractorOneBit IS
   PORT( 
      A     : IN     std_logic;
      B     : IN     std_logic;
      cin   : IN     std_logic;
      fcout : IN     std_logic;
      cout  : OUT    std_logic;
      sum   : OUT    std_logic
   );

-- Declarations

END SubstractorOneBit ;

--
-- VHDL Architecture Division_lib.SubstractorOneBit.struct
--
-- Created:
--          by - jschen3.ews (evrt-252-06.ews.illinois.edu)
--          at - 19:23:23 11/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Division_lib;

ARCHITECTURE struct OF SubstractorOneBit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;
   SIGNAL s    : std_logic;


   -- Component Declarations
   COMPONENT FA
   PORT (
      a    : IN     std_logic ;
      b    : IN     std_logic ;
      cin  : IN     std_logic ;
      S    : OUT    std_logic ;
      cout : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FA USE ENTITY Division_lib.FA;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout <= NOT(B);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(s, A, fcout)
   BEGIN
      CASE fcout IS
      WHEN '0' => sum <= s;
      WHEN '1' => sum <= A;
      WHEN OTHERS => sum <= 'X';
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_0 : FA
      PORT MAP (
         a    => A,
         b    => dout,
         cin  => cin,
         S    => s,
         cout => cout
      );

END struct;
