-- VHDL Entity Division_lib.subtract.symbol
--
-- Created:
--          by - jschen3.ews (evrt-252-06.ews.illinois.edu)
--          at - 19:29:44 11/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY subtract IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      S    : OUT    std_logic;
      cout : OUT    std_logic
   );

-- Declarations

END subtract ;

--
-- VHDL Architecture Division_lib.subtract.struct
--
-- Created:
--          by - jschen3.ews (evrt-252-06.ews.illinois.edu)
--          at - 19:29:44 11/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Division_lib;

ARCHITECTURE struct OF subtract IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;


   -- Component Declarations
   COMPONENT FA
   PORT (
      a    : IN     std_logic ;
      b    : IN     std_logic ;
      cin  : IN     std_logic ;
      S    : OUT    std_logic ;
      cout : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FA USE ENTITY Division_lib.FA;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout <= NOT(b);

   -- Instance port mappings.
   U_0 : FA
      PORT MAP (
         a    => a,
         b    => dout,
         cin  => cin,
         S    => S,
         cout => cout
      );

END struct;
