-- VHDL Entity project1_lib.z_test_encrypt_decrypt_ascii_mirror.symbol
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 00:48:39 11/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY z_test_encrypt_decrypt_ascii_mirror IS
   PORT( 
      mirror_in   : IN     std_logic_vector (7 DOWNTO 0);
      mirror_out1 : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END z_test_encrypt_decrypt_ascii_mirror ;

--
-- VHDL Architecture project1_lib.z_test_encrypt_decrypt_ascii_mirror.struct
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 00:48:39 11/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF z_test_encrypt_decrypt_ascii_mirror IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL mirror_out : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT z_ascii_mirror
   PORT (
      mirror_in  : IN     std_logic_vector (7 DOWNTO 0);
      mirror_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : z_ascii_mirror USE ENTITY project1_lib.z_ascii_mirror;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : z_ascii_mirror
      PORT MAP (
         mirror_in  => mirror_in,
         mirror_out => mirror_out
      );
   U_1 : z_ascii_mirror
      PORT MAP (
         mirror_in  => mirror_out,
         mirror_out => mirror_out1
      );

END struct;
