-- VHDL Entity project1_lib.add1.symbol
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 00:30:15 10/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY add1 IS
   PORT( 
      a_in  : IN     std_logic_vector (7 DOWNTO 0);
      cout  : OUT    std_logic;
      s_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END add1 ;

--
-- VHDL Architecture project1_lib.add1.struct
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 00:30:15 10/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY project1_lib;

ARCHITECTURE struct OF add1 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL b_in : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout : std_logic;


   -- Component Declarations
   COMPONENT full_adder_8bit_bus
   PORT (
      a_in  : IN     std_logic_vector (7 DOWNTO 0);
      b_in  : IN     std_logic_vector (7 DOWNTO 0);
      cin   : IN     std_logic ;
      cout  : OUT    std_logic ;
      s_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder_8bit_bus USE ENTITY project1_lib.full_adder_8bit_bus;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'gnd'
   b_in(1) <= '0';

   -- ModuleWare code(v1.9) for instance 'U_3' of 'gnd'
   dout <= '0';

   -- ModuleWare code(v1.9) for instance 'U_2' of 'vdd'
   b_in(0) <= '1';

   -- Instance port mappings.
   U_0 : full_adder_8bit_bus
      PORT MAP (
         a_in  => a_in,
         b_in  => b_in,
         cin   => dout,
         cout  => cout,
         s_out => s_out
      );

END struct;
