-- VHDL Entity project1_lib.j21mux.symbol
--
-- Created:
--          by - jschen3.ews (evrt-252-17.ews.illinois.edu)
--          at - 17:35:24 10/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY j21mux IS
   PORT( 
      S : IN     std_logic;
      X : IN     std_logic;
      Y : IN     std_logic;
      Z : OUT    std_logic
   );

-- Declarations

END j21mux ;

--
-- VHDL Architecture project1_lib.j21mux.struct
--
-- Created:
--          by - jschen3.ews (evrt-252-17.ews.illinois.edu)
--          at - 17:35:24 10/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF j21mux IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'and'
   dout2 <= dout AND X;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'and'
   dout1 <= S AND Y;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'inv'
   dout <= NOT(S);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'or'
   Z <= dout2 OR dout1;

   -- Instance port mappings.

END struct;
