-- VHDL Entity lab2_lib.full_adder.symbol
--
-- Created:
--          by - hkiang2.ews (linux-v1.ews.illinois.edu)
--          at - 00:43:12 09/14/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY full_adder IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      cout : OUT    std_logic;
      s    : OUT    std_logic
   );

-- Declarations

END full_adder ;

--
-- VHDL Architecture lab2_lib.full_adder.struct
--
-- Created:
--          by - hkiang2.ews (linux-v1.ews.illinois.edu)
--          at - 00:43:12 09/14/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lab2_lib;

ARCHITECTURE struct OF full_adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Y     : std_logic;
   SIGNAL din2  : std_logic;
   SIGNAL dout1 : std_logic;


   -- Component Declarations
   COMPONENT myxor
   PORT (
      X : IN     std_logic ;
      Y : IN     std_logic ;
      f : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : myxor USE ENTITY lab2_lib.myxor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout1 <= din2 AND cin;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   Y <= a AND b;

   -- Instance port mappings.
   U_0 : myxor
      PORT MAP (
         X => cin,
         Y => din2,
         f => s
      );
   U_1 : myxor
      PORT MAP (
         X => dout1,
         Y => Y,
         f => cout
      );
   U_2 : myxor
      PORT MAP (
         X => a,
         Y => b,
         f => din2
      );

END struct;
