-- VHDL Entity project1_lib.alphabet_5bit_decoder.symbol
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 01:04:32 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alphabet_5bit_decoder IS
   PORT( 
      din : IN     std_logic_vector (4 DOWNTO 0)
   );

-- Declarations

END alphabet_5bit_decoder ;

--
-- VHDL Architecture project1_lib.alphabet_5bit_decoder.struct
--
-- Created:
--          by - zmcgint2.ews (linux-v1.ews.illinois.edu)
--          at - 01:04:32 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF alphabet_5bit_decoder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_1' of 'decoder'

   -- Instance port mappings.

END struct;
