-- VHDL Entity lab22_lib.myxor.symbol
--
-- Created:
--          by - zmcgint2.ews (gelib-057-29.ews.illinois.edu)
--          at - 10:05:24 09/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY myxor IS
   PORT( 
      x : IN     std_logic;
      y : IN     std_logic;
      f : OUT    std_logic
   );

-- Declarations

END myxor ;

--
-- VHDL Architecture lab22_lib.myxor.struct
--
-- Created:
--          by - zmcgint2.ews (gelib-057-29.ews.illinois.edu)
--          at - 10:05:24 09/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF myxor IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'nand'
   dout2 <= NOT(x AND dout1);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'nand'
   dout1 <= NOT(x AND y);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'nand'
   dout3 <= NOT(dout1 AND y);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   f <= NOT(dout2 AND dout3);

   -- Instance port mappings.

END struct;
